= Contacts API


=== Find contacts
'''
Example how to find contacts by id, contact list, or on any property name.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindContactsRequest request = FindContactsRequest.create()
                .limit(1L)
                .offset(5L)
                .id(Arrays.asList(463633187003L, 466225637003L))
                .build();
    Page<Contact> contacts = client.contactsApi().find(request);



=== Get contact
'''
Example how to get contact by id. Deleted contacts can still be retrieved but will be marked deleted
and will not show up when quering contacts.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Contact contact = client.contactsApi().get(463633187003L);


=== Create contact
'''
Example how to create contacts in the CallFire system. These contacts are not validated on creation.
They will be validated upon being added to a campaign.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Contact contact = new Contact();
    contact.setHomePhone("16505044730");
    List<Contact> inputContacts = Arrays.asList(contact);
    List<ResourceId> resultResourceIds = client.contactsApi().create(inputContacts);


=== Update webhook
'''
Example how to update contact.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Contact contact = new Contact();
    contact.setId(463633187003L);
    contact.setHomePhone("16505044730");
    client.contactsApi().update(contact);



=== Delete contact
'''
Example how to delete contact by id. This does not actually delete the contact, it just removes the contact from
any contact lists and marks the contact as deleted so won't show up in queries anymore.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    client.contactsApi().delete(463633187003L);
