= Contact lists API


=== Find contact lists
'''
Example how to find contact lists by id, name, number, etc...
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindContactListsRequest request = FindContactListsRequest.create()
        .limit(1L)
        .offset(1L)
        .name("listName")
        .build();
    Page<ContactList> contactLists = client.contactListsApi().find(request);

=== Get contact list
'''
Example how to get contact list by id.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    ContactList contactList = client.contactListsApi().get(1026694003L);

=== Create contact list
'''
Contact lists can be created from existing single contacts (use their ids), contact objects and phone numbers.
 Example how to create contact list from plain numbers:
[source,java]
    CreateContactListRequest request = CreateContactListRequest.<String>create()
        .name("listFromNumbers")
        .contacts(asList("12135678881", "12135678882"))
        .build();
    ResourceId resourceId = client.contactListsApi().create(request);

Second example shows how to create contact list from existing contacts, what we need is just their ids:
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    CreateContactListRequest request = CreateContactListRequest.<Long>create()
        .name("listFromExistingContacts")
        .contacts(Arrays.asList(123L, 456L, 789L))
        .build();
    ResourceId resourceId = client.contactListsApi().create(request);

Next code sample uses *Contact* object in CreateContactListRequest request:
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Contact contact = new Contact();
    contact.setFirstName("John");
    contact.setHomePhone("16505044730");
    contact.getProperties().put("age", "30");
    CreateContactListRequest request = CreateContactListRequest.<Contact>create()
        .name("listFromContacts")
        .contacts(Arrays.asList(contact))
        .build();
    ResourceId resourceId = client.contactListsApi().create(request);

=== Create contact list from csv
'''
Example how to upload contact lists from CSV file. Max file size is limited to 10 Mb.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    File file = new File("/contacts/contacts-list.csv");
    ResourceId resourceId = client.contactListsApi().createFromCsv("New contact list", file);

=== Update contact list
'''
Example how to update contact list.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    UpdateContactListRequest request = UpdateContactListRequest.create()
        .id(1026694003L)
        .name("sampleListName").
        build();
    client.contactListsApi().update(request);

=== Delete contact list
'''
Example how to delete contact list.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    client.contactListsApi().delete(463633187003L);
