= DNC lists API


=== Find dnc lists
'''
Example how to find all do not contact (DNC) lists.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindDncListsRequest request = FindDncListsRequest.create().build();
    Page<DncList> dncList = client.dncListsApi().find(request);

=== Create dnc list
'''
Example how to create do not contact (DNC) list.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    DncList dncList = new DncList();
    dncList.setName("myDncList");
    ResourceId res = client.dncListsApi().create(dncList);

=== Get universal dnc numbers
'''
Example how to search Universal Do Not Contact by number
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    List<UniversalDnc> universalDncNumbers = client.dncListsApi().getUniversalDncNumber("16502572135", "16502572136");

=== Get dnc list
'''
Example how to get DNC list by id
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    DncList dncList = client.dncListsApi().get(1975140003L);

=== Delete dnc list
'''
Example how to delete DNC list
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    client.dncListsApi().delete(1975140003L);

=== Get dnc list items
'''
Example how to get second 5 DNC items from list
Property <b>request.id</b> required
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    GetByIdRequest request = GetByIdRequest.create()
        .limit(5L)
        .offset(5L)
        .id(1975140003L)
        .build();
    Page<DoNotContact> dncs = client.dncListsApi().getListItems(request);

=== Add dnc list item
'''
Example how to add 3 DNC items to list
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    DoNotContact dnc1 = new DoNotContact();
    dnc1.setNumber("12135543211");
    dnc1.setText(true);
    dnc1.setCall(false);
    DoNotContact dnc2 = new DoNotContact();
    dnc2.setNumber("12135543212");
    dnc2.setText(true);
    dnc2.setCall(false);
    DoNotContact dnc3 = new DoNotContact();
    dnc3.setNumber("12135543213");
    dnc3.setText(true);
    dnc3.setCall(true);
    AddDncListItemsRequest request = AddDncListItemsRequest.<DoNotContact>create()
        .contactListId(dncListId.getId())
        .contacts(Arrays.asList(dnc1, dnc2, dnc3))
        .build();
    // add items
    client.dncListsApi().addListItems(request);

=== Remove dnc list item
'''
Example how to delete DNC list item (you should specify list id and phone number to delete)
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    client.dncListsApi().removeListItem(1975140003L, "16505044730");

=== Remove dnc list item
'''
Example how to delete DNC list items (you should specify list id and phone numbers to delete)
[source,java]
    //toNumber param is required
    CallfireClient client = new CallfireClient("api login", "api password");
    client.dncListsApi().removeListItems(1975140003L, Arrays.asList("16505044730", "16505044731"));
