= Calls API


=== Find calls
'''
Example how to find all calls sent or received by the user. Use "id=0" for the campaignId parameter to query for all
 calls sent through the POST /calls API.
[source,java]
    //No one parameter is required
    FindCallsRequest request = FindCallsRequest.create()
        .id(Arrays.asList(617067920003L))
        .campaignId(7373801003L)
        .fromNumber("12132609784")
        .toNumber("12132212384")
        .build();
    CallfireClient client = new CallfireClient("api_login", "api_password");
    Page<Call> calls = client.callsApi().find(request);

=== Send call
'''
Example how to use the /calls API to quickly send individual calls via default campaign. A verified Caller ID and
 sufficient credits are required to make a call.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    //Only "recipients" param required
    CallRecipient r1 = new CallRecipient();
    r1.setPhoneNumber("12132609784");
    r1.setLiveMessage("Hello");
    r1.setTransferMessage("transferTestMessage");
    //or you can use transfer sound id
    r1.setTransferMessageSoundId(1123123L);
    r1.setTransferNumber("14246525473");
    r1.setTransferDigit("1");
    List<CallRecipient> recipients = Arrays.asList(r1);
    List<Call> calls = client.callsApi().send(recipients);

In case you want to send call via existing campaign provide campaign id as second parameter for send() method,
 see example below:
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CallRecipient recipient = new CallRecipient();
    recipient.setPhoneNumber("12132609784");
    recipient.setLiveMessage("Hello");
    List<Call> calls = client.callsApi().send(Arrays.asList(recipient), 60000000003L);

Also you can send call with some default parameters which will be used in case when recipient doesn't have that info specified,
 see example below:
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CallRecipient recipient = new CallRecipient();
    recipient.setPhoneNumber("12132609784");
    SendCallsRequest request = SendCallsRequest.create()
        .recipients(asList(recipient))
        .campaignId(60000000003L)
        .defaultLiveMessage("defaultLive")
        .defaultMachineMessage("defaultMachine")
        .defaultVoice(Voice.FRENCHCANADIAN1)
        .build();
    List<Call> calls = client.callsApi().send(request);
    SendCallsRequest request = SendCallsRequest.create()
        .recipients(asList(recipient))
        .campaignId(60000000003L)
        .defaultLiveMessageSoundId(1213213L)
        .defaultMachineMessageSoundId(13132132L)
        .defaultVoice(Voice.FRENCHCANADIAN1)
        .build();
    calls = client.callsApi().send(request);

=== Get call
'''
Example how to return a single Call instance for a given call id.
[source,java]
    //Only "id" param required
    CallfireClient client = new CallfireClient("api_login", "api_password");
    Call call = client.callsApi().get(617067920003L);

=== Get call recordings
'''
Example how to return call recordings for a given call id.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    List<CallRecording> recs = client.callsApi().getCallRecordings(1232L, "items(callId)");

=== Get call recording by name and call id
'''
Example how to return call recording for a given call by recording name.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CallRecording recording = client.callsApi().getCallRecordingByName(1234L, "testName", "callId");

=== Get mp3 call recording by name and call id
'''
Example how to return mp3 call recording for a given call by recording name.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    InputStream is = client.callsApi().getCallRecordingMp3ByName(1234L, "testName");

=== Get call recording by id
'''
Example how to return call recording for a given recording id.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CallRecording rec = client.callsApi().getCallRecording(1234L, "campaignId");

=== Get mp3 call recording by id
'''
Example how to return mp3 call recording for a given recording id.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    InputStream is = client.callsApi().getCallRecordingMp3(1234L);


