= Calls API


=== Find calls
'''
Example how to find all calls sent or received by the user. Use "id=0" for the campaignId parameter to query for all
calls sent through the POST /calls API.
[source,java]
 //No one parameter is required
 FindCallsRequest request = FindCallsRequest.create()
        .id(Arrays.asList(617067920003L))
        .campaignId(7373801003L)
        .fromNumber("12132609784")
        .toNumber("12132212384")
        .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<Call> texts = client.callsApi().find(request);



=== Send call
'''
Example how to use the /calls API to quickly send individual calls. A verified Caller ID and sufficient credits
are required to make a call.
[source,java]
 //Only "recipients" param required
 CallRecipient r1 = new CallRecipient();
 r1.setPhoneNumber("12132609784");
 r1.setLiveMessage("Hello");
 List<CallRecipient> recipients = Arrays.asList(r1);
 CallfireClient client = new CallfireClient("api_login", "api_password");
 List<Text> texts = client.callsApi().send(recipients, 7373801003L);



=== Get call
'''
Example how to return a single Call instance for a given call id.
[source,java]
 //Only "id" param required
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Call call = client.callsApi().get(617067920003L);
