= TEXT APIs Specification


find api
-------
TIP: Finds all texts sent or received by the user. Use "campaignId=0" parameter to query for all texts sent through
the POST /texts API. If no limit is given then the last 100 texts will be returned.
****
[source,java]
 //No one parameter is required , you can only use parameters needed for you, others can be missed
 FindTextsRequest request = FindTextsRequest.create()
             .id(ArrayList<Long>)
             .campaignId(<Long>)
             .fromNumber(<String>)
             .toNumber(<String>)
             .label(<Long>)
             .states(ArrayList<State>))
             .results(ArrayList<TextRecord.TextResult>)
             .inbound(<Boolean>)
             .intervalBegin(<Date>)
             .intervalEnd(<Date>)
             .limit(<Long>)
             .offset(<Long>)
             .fields(<String>)
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<Text> texts = client.textsApi().find(request);
****

[NOTE]
=====================================================================
=====================================================================
[width="40%",frame="topbot",options="header,footer"]
|======================
|Parameter        |Description
|id               |(ArrayList<Long>), text id
|label            |(<Long>), label of the text message
|states           |(ArrayList<State>)), Expected text statuses in comma seperated string (READY, SELECTED, CALLBACK, FINISHED, DISABLED, DNC, DUP, INVALID, TIMEOUT, PERIOD_LIMIT).
|results          |(ArrayList<TextRecord.TextResult>), Expected text results in comma seperated string (SENT, RECEIVED, DNT, TOO_BIG, INTERNAL_ERROR, CARRIER_ERROR, CARRIER_TEMP_ERROR, UNDIALED).
|inbound          |(<Boolean>), Specify true if inbounds, false if outbounds. Do not specify for both.
|intervalBegin    |(<Date>), Start of the find interval in Unix time milliseconds.
|intervalEnd      |(<Date>), End of the find interval in Unix time milliseconds.
|                 |
|limit            |(<Long>), Maximum number of records to return in a paged list response. The default is 100.
|offset           |(<Long>), Offset to the start of a given page. The default is 0.
|fields           |(<String>), Limit fields returned. E.g. fields=id,name or fields=items(id,name).
|======================




send api
-------
TIP: Use the /calls API to quickly send individual calls. A verified Caller ID and sufficient credits are required to make a call.
****
[source,java]
 //Only "recipients" param required
 TextRecipient r1 = new TextRecipient();
 r1.setPhoneNumber(<String>);
 r1.setMessage(<String>);
 TextRecipient r2 = new TextRecipient();
 r2.setPhoneNumber(<String>);
 r2.setMessage(<String>);
 List<TextRecipient> recipients = Arrays.asList(r1, r2);
 CallfireClient client = new CallfireClient("api_login", "api_password");
 List<Text> texts = client.textsApi().send(recipients, campaignId(<Long>), fields(<String>));
****

[NOTE]
=====================================================================
=====================================================================
[width="40%",frame="topbot",options="header,footer"]
|======================
|Parameter        |Description
|id               |<Long>, text id
|fields           |<String>, Limit fields returned. E.g. fields=id,name or fields=items(id,name). (not necessary)
|======================



get api
-------
TIP: Returns a single Text instance for a given text id.
****
[source,java]
 //Only "id" param required
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Text text = client.textsApi().get(id(<Long>));
****

[NOTE]
=====================================================================
=====================================================================
[width="40%",frame="topbot",options="header,footer"]
|======================
|Parameter        |Description
|id               |<Long>, text id
|fields           |<String>, Limit fields returned. E.g. fields=id,name or fields=items(id,name). (not necessary)
|======================

