= Agent Groups API

== Find
Example how to find all agent groups which have *test-group* substring in name and return objects with ID only.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    FindAgentGroupsRequest request = FindAgentGroupsRequest.create()
        .limit(100L)
        .offset(0L)
        .fields("items(id)")
        .name("test-group")
        .build();
    Page<AgentGroup> agentGroupPage = callfireClient.agentGroupsApi().find(request);
    System.out.println(agentGroupPage);

== Create
Example how to create agent group with 2 existing agents:
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Agent agent1 = new Agent();
    agent1.setId(123L);
    Agent agent2 = new Agent();
    agent2.setId(456L);
    AgentGroup agentGroup = new AgentGroup();
    agentGroup.setName("test-group");
    agentGroup.setAgents(Arrays.asList(agent1, agent2));
    ResourceId groupId = callfireClient.agentGroupsApi().create(agentGroup1);

== Get
Get agent group by ID
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    AgentGroup agentGroup = callfireClient.agentGroupsApi().get(123L);
    System.out.println(agentGroup);

== Update
How to change group name and add new agent:
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    AgentGroup agentGroup = callfireClient.agentGroupsApi().get(123L);
    Agent newAgent = new Agent();
    newAgent.setId(456L);
    agentGroup.setName("new-test-group");
    agentGroup.setAgents(Arrays.asList(newAgent));
    callfireClient.agentGroupsApi().update(agentGroup);

== Delete
Delete particular agent group by ID
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    callfireClient.agentGroupsApi().delete(123L);