= Agents API


=== Find agents
Example how to find all agents within particular group.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    FindAgentsRequest request = FindAgentsRequest.create()
        .agentGroupName("agent-group")
        .build();
    Page<Agent> agentPage = client.agentsApi().find(request);
    System.out.println(agentPage);

=== Get agent
Get agent by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Agent agent = client.agentsApi().get(1234L);
    System.out.println(agent);

=== Find agent sessions
Example how to find all sessions of particular agent.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    FindAgentSessionsRequest request = FindAgentSessionsRequest.create()
        .agentEmail("dev+agent@callfire.com")
        .build();
    Page<AgentSession> sessionPage = client.agentsApi().findSessions(request);
    System.out.println(sessionPage);

=== Get agent session
Get agent session by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    AgentSession session = client.agentsApi().getSession(1234L);
    System.out.println(session);
