= Call broadcasts API


=== Find broadcasts
Find all call campaigns created by the user. Can query on label, name, and the current running status of the campaign.
 Returns a paged list of call broadcasts. Example how to find 2 call broadcasts which have 'campaign'
 suffix in their names:
[source,java]
    FindCallBroadcastsRequest request = FindCallBroadcastsRequest.create()
        .name("campaign")
        .limit(2L)
        .build();
    Page<CallBroadcast> broadcasts = client.callBroadcastsApi().find(request);
    System.out.println(broadcasts);

=== Create broadcast
Create a call broadcast campaign using the Call Broadcast API. Send a CallBroadcast in the message body to detail
 a call broadcast campaign. A campaign can be created with no contacts and bare minimum configuration, but contacts
 will have to be added further on to use the campaign.
 Example how to create call broadcast and then start it:
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    CallBroadcast broadcast = new CallBroadcast();
    broadcast.setName("Example VB");
    broadcast.setFromNumber("12135551189");
    broadcast.setAnsweringMachineConfig(AnsweringMachineConfig.AM_AND_LIVE);
    CallBroadcastSounds sounds = new CallBroadcastSounds();
    sounds.setLiveSoundTextVoice(Voice.MALE1);
    sounds.setLiveSoundText("Hello! This is a live answer text to speech recording");
    sounds.setMachineSoundText("This is an answering machine text to speech recording");
    sounds.setMachineSoundTextVoice(Voice.MALE1);
    broadcast.setSounds(sounds);
    // set recipients
    Recipient recipient1 = new Recipient();
    recipient1.setPhoneNumber("12135551100");
    Recipient recipient2 = new Recipient();
    recipient2.setPhoneNumber("12135551101");
    broadcast.setRecipients(Arrays.asList(recipient1, recipient2));
    // create broadcast with 'start' argument = true to start campaign immediately
    ResourceId id = callfireClient.callBroadcastsApi().create(broadcast, true);

=== Get broadcast
Get call broadcast by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    CallBroadcast broadcast = callfireClient.callBroadcastsApi().get(123L);

=== Update broadcast
After having created an call broadcast campaign, this method lets the user modify the configuration of
 a call broadcast campaign. See example how to add local time restrictions.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    CallBroadcast broadcast = callfireClient.callBroadcastsApi().get(123L);
    // time restrictions
    LocalTimeRestriction restrictions = new LocalTimeRestriction();
    restrictions.setBeginHour(10);
    restrictions.setBeginMinute(10);
    restrictions.setEndHour(22);
    restrictions.setEndMinute(0);
    restrictions.setEnabled(true);
    broadcast.setLocalTimeRestriction(restrictions);
    // update campaign
    callfireClient.callBroadcastsApi().update(broadcast);

== Start broadcast
Start call broadcast by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    callfireClient.callBroadcastsApi().start(123L);

== Stop broadcast
Stop call broadcast by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    callfireClient.callBroadcastsApi().stop(123L);

== Archive broadcast
Archive call broadcast by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    callfireClient.callBroadcastsApi().archive(123L);

== Get broadcast calls
Get calls associated with call broadcast ordered by date.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    GetByIdRequest request = GetByIdRequest.create()
        .id(1234L)
        .build();
    Page<Call> calls = callfireClient.callBroadcastsApi().getCalls(request);
    System.out.println(calls);

== Get broadcast stats
Get broadcast statistics.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Date end = new Date();
    Date begin = DateUtils.addDays(end, -5);
    String fields = "callsAttempted,callsPlaced,callsDuration";
    CallBroadcastStats stats = api.getStats(8624192003L, fields, begin, end);
    System.out.println(stats);

== Add recipients to an call broadcast
Use this method to add recipients to an already created call broadcast. Post a list of Recipient objects for
 them to be immediately added to the call broadcast campaign. These contacts do not go through validation process,
 and will be acted upon as they are added. Recipients may be added as a list of contact ids, or list of numbers.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Recipient recipient1 = new Recipient();
    recipient1.setPhoneNumber("12131234567");
    Recipient recipient2 = new Recipient();
    recipient2.setPhoneNumber("12131234568");
    List<Call> calls = callfireClient.callBroadcastsApi().addRecipients(id, Arrays.asList(recipient1, recipient2));
    System.out.println(calls);

== Get all broadcast batches
This method will enable the user to page through all of the batches for a particular call broadcast campaign.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    GetByIdRequest request = GetByIdRequest.create()
        .id(1234L)
        .limit(10L)
        .build();
    Page<Batch> batches = callfireClient.callBroadcastsApi().getBatches(request);
    System.out.println(batches);

== Add batch to broadcast
The add batch method allows the user to add additional batches to an already created call broadcast campaign.
 The added batch will go through the CallFire validation process, unlike in the recipients version of this API.
 Because of this, use the scrubDuplicates flag to remove duplicates from your batch. Batches may be added as a
 contact list id, a list of contact ids, or a list of numbers.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Recipient recipient1 = new Recipient();
    recipient1.setPhoneNumber("12131234567");
    Recipient recipient2 = new Recipient();
    recipient2.setPhoneNumber("12131234568");
    AddBatchRequest request = AddBatchRequest.create()
        .campaignId(id)
        .name("new_batch")
        .scrubDuplicates(true)
        .recipients(Arrays.asList(recipient1, recipient2))
        .build();
    ResourceId resourceId = callfireClient.callBroadcastsApi().addBatch(request);

