= Campaign Sounds API


=== Find campaign sounds
Find all campaign sounds that were created by the user. These are all of the available sounds to be used in campaigns.
 Example how to find 3 campaign sounds and filter by name "sample".
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    FindSoundsRequest request = FindSoundsRequest.create()
        .limit(3L)
        .filter("sample")
        .build();
    Page<CampaignSound> campaignSounds = callfireClient.campaignSoundsApi().find(request);

=== Get sound metadata
Returns a single CampaignSound instance for a given campaign sound id. This is the meta data to the sounds only.
 No audio data is returned from this API.
 Example how to get sound metadata by ID only with name, status and lengthInSeconds fields, to get whole object, just
 call *campaignSoundsApi.get(id)* method without fields argument.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Long id = 12345L;
    CampaignSound campaignSound = callfireClient.campaignSoundsApi().get(id, "name,status,lengthInSeconds");

=== Download MP3 sound
Download the MP3 version of the hosted file.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    InputStream is = callfireClient.campaignSoundsApi().getMp3(12345L);

=== Download WAV sound
Download the WAV version of the hosted file.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    InputStream is = callfireClient.campaignSoundsApi().getWav(12345L);

=== Add sound via call
Use this API to create a sound via phone call. Supply the required phone number in the CallCreateSound object
 inside of the request, and the user will receive a call shortly after with instructions on how to record a
 sound over the phone.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    CallCreateSound callCreateSound = new CallCreateSound();
    callCreateSound.setName("CallInSound_1");
    callCreateSound.setToNumber("12131234567");
    ResourceId resourceId = callfireClient.campaignSoundsApi().recordViaPhone(callCreateSound);
    System.out.println(resourceId.getId());

If you want to see created sound details please use code like:
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    CallCreateSound callCreateSound = new CallCreateSound();
    callCreateSound.setName("CallInSound_1");
    callCreateSound.setToNumber("12131234567");
    CampaignSound sound = callfireClient.campaignSoundsApi().recordViaPhoneAndGetSoundDetails(callCreateSound);
    System.out.println(resourceId.getId());

=== Add sound via text-to-speech
Use this API to create a sound file via a supplied string of text. Send the required text in the
 TextToSpeech.message field, and pick a voice in the TextToSpeech.voice field. Available voices are:
 MALE1, FEMALE1 , FEMALE2, SPANISH1, FRENCHCANADIAN1, see Voice enum.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    TextToSpeech tts = new TextToSpeech();
    tts.setVoice(Voice.FEMALE1);
    tts.setMessage("this is TTS message from java client");
    ResourceId resourceId = callfireClient.campaignSoundsApi().createFromTts(tts);
    CampaignSound campaignSound = callfireClient.campaignSoundsApi().get(resourceId.getId());

If you want to see created sound details please use code like:
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    TextToSpeech tts = new TextToSpeech();
    tts.setVoice(Voice.FEMALE1);
    tts.setMessage("this is TTS message from java client");
    CampaignSound sound = callfireClient.campaignSoundsApi().createFromTtsAndGetSoundDetails(tts);
