= Subscriptions API

=== Find subscriptions
'''
Search for subscriptions on campaign, trigger event, format, fromNumber, toNumber.
 Example how to get first 5 subscriptions which are assigned to campaign with id 1000000L and have formatted as JSON.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindSubscriptionsRequest request = FindSubscriptionsRequest.create()
        .limit(5L)
        .campaignId(1000000L)
        .format(NotificationFormat.JSON)
        .build();
    Page<Subscription> subscriptions = client.subscriptionsApi().find(request);

=== Get subscription
'''
Example how to get a single Subscription instance for a given subscription id.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Subscription subscription = client.subscriptionApi().get(12345678L, "id,name,created");

=== Create subscription
'''
Example how to create a subscription for campaign. Callfire will query your callback URL with http POST request when
 specified campaign has FINISHED.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Subscription subscription = new Subscription();
    subscription.setEnabled(true);
    subscription.setEndpoint("http://www.example.com/endpoint");
    subscription.setNotificationFormat(NotificationFormat.JSON);
    subscription.setBroadcastId(1400000L);
    subscription.setTriggerEvent(TriggerEvent.CAMPAIGN_FINISHED);
    ResourceId id = client.subscriptionsApi().create(subscription);

=== Update subscription
'''
Example how to update the information in a currently existing subscription. Most fields are updatable.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Subscription subscription = client.subscriptionsApi().get(123456L);
    subscription.setTriggerEvent(TriggerEvent.CAMPAIGN_STARTED);
    subscription.setCallback("https://yoursite.com/callback");
    client.subscriptionsApi().update(subscription);

=== Delete subscription
'''
Example how to delete a subscription. Will be removed permanently.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    client.subscriptionsApi().delete(12345678L);
