= Webhooks API


=== Find webhooks
'''
Search for webhooks on name, resource, event, callback URL, or whether they are enabled.
 Example how to get first 5 webhooks which are *enabled* and assigned to resource *"textBroadcast"*.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindWebhooksRequest request = FindWebhooksRequest.create()
        .limit(5L)
        .enabled(true)
        .name("test_name")
        .build();
    Page<Webhook> webhooks = client.webhooksApi().find(request);

=== Get webhook
'''
Example how to get a single Webhook instance for a given webhook id.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Webhook webhook = client.webhooksApi().get(12345678L, "id,name,created");

=== Create webhook
'''
Example how to create a webhook for voice campaign. Callfire will query your callback URL with http POST request when
 any campaign has STARTED or FINISHED.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Webhook webhook = new Webhook();
    webhook.setName("new webhook");
    webhook.setResource(ResourceType.CALL_BROADCAST);
    webhook.getEvents().add(ResourceEvent.STARTED);
    webhook.getEvents().add(ResourceEvent.FINISHED);
    webhook.setCallback("https://yoursite.com/callback");
    Long id = client.webhooksApi().create(webhook);

=== Update webhook
'''
Example how to update the information in a currently existing webhook. Most fields are updatable.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Webhook webhook = client.webhooksApi().get(12345678L);
    webhook.setName("new webhook");
    webhook.setResource(ResourceType.CALL_BROADCAST);
    webhook.getEvents().add(ResourceEvent.STARTED);
    webhook.getEvents().add(ResourceEvent.FINISHED);
    webhook.setCallback("https://yoursite.com/callback");
    client.webhooksApi().update(webhook);

=== Delete webhook
'''
Example how to delete a webhook. Will be removed permanently.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    client.webhooksApi().delete(12345678L);

=== Find webhook resources
'''
Example how to find webhook resources.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    WebhooksApi api = client.webhooksApi();
    List<WebhookResource> resources = api.findWebhookResources("items(resource)");

=== Find webhook resource
'''
Example how to find webhook resource.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    WebhooksApi api = client.webhooksApi();
    WebhookResource resource = api.findWebhookResource(ResourceType.CALL_BROADCAST, "resource");
