= Webhooks API


=== Find webhooks
'''
Search for webhooks on name, resource, event, callback URL, or whether they are enabled.
Example how to get first 5 webhooks which are *enabled* and assigned to resource *"textBroadcast"*.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    FindWebhooksRequest request = FindWebhooksRequest.create()
        .limit(5L)
        .enabled(true)
        .resource("textBroadcast")
        .build();
    Page<Webhook> webhooks = client.webhooksApi().find(request);

=== Get webhook
'''
Example how to get a single Webhook instance for a given webhook id
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Webhook webhook = client.webhooksApi().get(12345678L, "id,name,created");


=== Update webhook
'''
Example how to update the information in a currently existing webhook. Most fields are updatable.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    Webhook webhook = client.webhooksApi().get(12345678L);
    webhook.setName("new webhook");
    webhook.setResource("voiceBroadcast");
    webhook.setEvents(new HashSet<>(Collections.singletonList("stop")));
    webhook.setCallback("https://yoursite.com/callback");
    client.webhooksApi().update(webhook);

=== Delete webhook
'''
Example how to delete a webhook. Will be removed permenantly.
[source,java]
    CallfireClient client = new CallfireClient("api login", "api password");
    client.webhooksApi().delete(12345678L);
