= Number leases API


=== Find number leases
'''
Example how to find all number leases for the user. This API is useful for finding all numbers currently owned by an account.
[source,java]
 //At least one parameter is required
 FindNumberLeasesRequest request = FindNumberLeasesRequest.create()
             .city("REDWOOD CITY")
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<NumberLease> leases = client.numberLeasesApi().find(request);



=== Get number lease
'''
Example how to return a single NumberLease instance for a given number lease.
[source,java]
 //Only "number" param required
 CallfireClient client = new CallfireClient("api_login", "api_password");
 NumberLease lease = client.numberLeasesApi().get("16502572135");



=== Update number lease
'''
Example how to update a number lease instance. Ability to turn off autoRenew and toggle call/text features for a particular number.
[source,java]
 NumberLease lease = new NumberLease();
 lease.setNumber("16502572135");
 lease.setAutoRenew(true);
 CallfireClient client = new CallfireClient("api_login", "api_password");
 client.numberLeasesApi().update(lease);



=== Find number leases configs
'''
Example how to find all number lease configs for the user.
[source,java]
 //At least one parameter is required
 FindNumberLeaseConfigsRequest request = FindNumberLeaseConfigsRequest.create()
             .city("REDWOOD CITY")
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<NumberConfig> configs = client.numberLeasesApi().findConfigs(request);



=== Get number leases config
'''
Example how to return a single NumberConfig instance for a given number lease.
[source,java]
 //Only "number" param required
 CallfireClient client = new CallfireClient("api_login", "api_password");
 NumberConfig config = client.numberLeasesApi().getConfig("16502572135");



=== Update number lease config
'''
Example how to update a number lease config. Use this API endpoint to add an Inbound IVR or Call Tracking
feature to a CallFire phone number.
[source,java]
  NumberConfig config = new NumberConfig();
  config.setNumber("16502572135");
  config.setConfigType(<ConfigType>);
  CallTrackingConfig callTrackingConfig = new CallTrackingConfig();
  callTrackingConfig.setScreen(true);
  callTrackingConfig.setRecorded(true);
  callTrackingConfig.setTransferNumbers(Arrays.asList("16502572136", "16502572137"));
  config.setCallTrackingConfig(callTrackingConfig);
  CallfireClient client = new CallfireClient("api_login", "api_password");
  client.numberLeasesApi().updateConfig(config);

