= Number leases API


=== Find number leases
'''
Example how to find number leases of particular local numbers for the user. This API is useful for finding all numbers
 currently owned by an account. In that case send empty find request: *FindNumberLeasesRequest.create().build()*.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    FindNumberLeasesRequest request = FindNumberLeasesRequest.create()
        .city("REDWOOD CITY")
        .build();
    Page<NumberLease> leases = client.numberLeasesApi().find(request);

=== Get number lease
'''
Example how to return a single NumberLease instance for a given number lease.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    NumberLease lease = client.numberLeasesApi().get("16502572135");

=== Update number lease
'''
Example how to update a number lease instance. Ability to turn off autoRenew and toggle call/text features for a
 particular number.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    NumberLease lease = new NumberLease();
    lease.setNumber("16502572135");
    lease.setAutoRenew(true);
    client.numberLeasesApi().update(lease);

=== Find number leases configs
'''
Example how to find all number lease configs for the user.
[source,java]
    FindNumberLeaseConfigsRequest request = FindNumberLeaseConfigsRequest.create().build();
    CallfireClient client = new CallfireClient("api_login", "api_password");
    Page<NumberConfig> configs = client.numberLeasesApi().findConfigs(request);

=== Get number leases config
'''
Example how to return a single NumberConfig instance for a given number lease.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    NumberConfig config = client.numberLeasesApi().getConfig("16502572135");

=== Update number lease config
'''
Example how to update a number lease config. Use this API endpoint to add an Inbound IVR or Call Tracking
 feature to a CallFire phone number.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    NumberConfig config = new NumberConfig();
    config.setNumber("16502572135");
    config.setConfigType(ConfigType.TRACKING);
    // create call tracking config
    CallTrackingConfig callTrackingConfig = new CallTrackingConfig();
    callTrackingConfig.setScreen(true);
    callTrackingConfig.setRecorded(true);
    callTrackingConfig.setTransferNumbers(Arrays.asList("16502572136", "16502572137"));
    callTrackingConfig.setVoicemail(true);
    callTrackingConfig.setIntroSoundId(1234L);
    callTrackingConfig.setVoicemailSoundId(1234L);
    callTrackingConfig.setFailedTransferSoundId(1234L);
    callTrackingConfig.setWhisperSoundId(1234L);
    WeeklySchedule weeklySchedule = new WeeklySchedule();
    weeklySchedule.setStartTimeOfDay(new LocalTime(1, 1, 1));
    weeklySchedule.setStopTimeOfDay(new LocalTime(2, 2, 2));
    weeklySchedule.setDaysOfWeek(new HashSet<>(Arrays.asList(DayOfWeek.MONDAY, DayOfWeek.FRIDAY)));
    weeklySchedule.setTimeZone("America/Los_Angeles");
    callTrackingConfig.setWeeklySchedule(weeklySchedule);
    GoogleAnalytics googleAnalytics = new GoogleAnalytics();
    googleAnalytics.setCategory("Sales");
    googleAnalytics.setGoogleAccountId("UA-12345-26");
    googleAnalytics.setDomain("testDomain");
    callTrackingConfig.setGoogleAnalytics(googleAnalytics);
    config.setCallTrackingConfig(callTrackingConfig);
    // update number lease
    client.numberLeasesApi().updateConfig(config);
