= Numbers API


=== Find local numbers
'''
Example how to find numbers in the CallFire local numbers catalog that are available for purchase.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    //At least one parameter is required
    FindNumbersLocalRequest request = FindNumbersLocalRequest.create()
        .state("LA")
        .build();
    List<Number> numbers = client.numbersApi().findNumbersLocal(request);

=== Find number regions
'''
Use this API to obtain detailed region information that can then be used to query for more specific phone numbers
 than a general query. Example below shows how to find number region information for specified state and zip code.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    //At least one parameter is required
    FindNumberRegionsRequest request = FindNumberRegionsRequest.create()
        .limit(2L)
        .state("IL")
        .zipcode("60640")
        .build();
    Page<Region> regions = client.numbersApi().findNumberRegions(request);

=== Find numbers tollfree
'''
Example how to find numbers in the CallFire tollfree numbers catalog that are available for purchase.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CommonFindRequest request = CommonFindRequest.create()
        .limit(1L)
        .offset(1L)
        .build();
    List<Number> numbers = client.numbersApi().findNumbersTollfree(request);
