= Numbers API


=== Find local numbers
'''
Example how to find numbers in the CallFire local numbers catalog that are available for purchase.
[source,java]
 //At least one parameter is required
 FindNumbersLocalRequest request = FindNumbersLocalRequest.create()
             .city("LOS ANGELES")
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 List<Number> numbers = client.numbersApi().findNumbersLocal(request);



=== Find number regions
'''
Example how to find number region information. Use this API to obtain detailed region information that can then be used to query
for more specific phone numbers than a general query.
[source,java]
 //At least one parameter is required
 FindNumberRegionsRequest request = FindNumberRegionsRequest.create()
             .city("LOS ANGELES")
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<Region> regions = client.numbersApi().findNumberRegions(request);



=== Find numbers tollfree
'''
Example how to find numbers in the CallFire tollfree numbers catalog that are available for purchase.
[source,java]
 //No params required, you can run query only with basic authentification
 CommonFindRequest request = CommonFindRequest.create()
             .limit(1L)
             .offset(1L)
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 List<Number> numbers = client.numbersApi().findNumbersTollfree(request);
