= User account API

== Account specific APIs

=== Get account info
Example how to get account information like name, surname, email, account permissions.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    Account account = callfireClient.meApi().getAccount();
    System.out.println(account);

=== Get billing plan usage info
Example how to find billing plan usage for the user. Returns billing plan usage for the current month.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    BillingPlanUsage billingPlanUsage = callfireClient.meApi().getBillingPlanUsage();
    System.out.println(billingPlanUsage);

=== Get credits usage info
Example how find credit usage for the user. Returns credits usage for time period specified or if unspecified then total for all time.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    DateIntervalRequest request = DateIntervalRequest.create()
        .intervalBegin(DateUtils.addMonths(new Date(), -2))
        .intervalEnd(new Date())
        .build();
    CreditsUsage creditUsage = callfireClient.meApi().getCreditUsage(request);
    System.out.println(creditUsage);

=== Get account caller IDs
Example how to get a list of verified caller ids. If the number is not shown in the list, then it is not verified,
 and will have to send for a verification code.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    List<CallerId> callerIds = callfireClient.meApi().getCallerIds();
    System.out.println(callerIds);

=== Send verification code to caller ID
Example how to send a verification code to the phone number. The verification code is delivered
 via a phone call. This code needs to be submitted to the verify caller id API endpoint.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    String phoneNumber = "12132224444";
    callfireClient.meApi().sendVerificationCode(phoneNumber);

=== Verify caller ID
You can verify your caller ID with the verification code received from the previous operation, a call to this
 endpoint is required to finish verification.
[source,java]
    CallfireClient callfireClient = new CallfireClient("api_login", "api_password");
    String phoneNumber = "12132224444";
    CallerIdVerificationRequest request = CallerIdVerificationRequest.create()
        .callerId(phoneNumber)
        .verificationCode("1234")
        .build();
    Boolean verified = callfireClient.meApi().verifyCallerId(request);

== API credentials CRUD operations
*/me* endpoint has operations to *find, create, get and delete* API user credentials. To execute one of these
 operations you should create *CallfireClient* with your regular account credentials not API one, because only
 account holder can manipulate API users.


=== Create API credentials
Example how to create API user.
[source,java]
    CallfireClient callfireClient = new CallfireClient("account_login", "account_password");
    ApiCredentials credentials = new ApiCredentials();
    credentials.setName("api user");
    credentials = callfireClient.meApi().createApiCredentials(credentials);
    System.out.println(credentials);

=== Find API credentials
Example how to get first 2 API users.
[source,java]
    CallfireClient callfireClient = new CallfireClient("account_login", "account_password");
    CommonFindRequest request = CommonFindRequest.create()
        .limit(2L)
        .build();
    Page<ApiCredentials> credentials = callfireClient.meApi().findApiCredentials(request);
    System.out.println(credentials);

=== Get API credentials
Example how to get particular API user and limit returned fields to name and enabled flag.
[source,java]
    CallfireClient callfireClient = new CallfireClient("account_login", "account_password");
    ApiCredentials credentials = callfireClient.meApi().getApiCredentials(123456L, "name,enabled");
    System.out.println(credentials);

=== Delete API credentials
Example how to delete particular API user by ID.
[source,java]
    CallfireClient callfireClient = new CallfireClient("account_login", "account_password");
    callfireClient.meApi().deleteApiCredentials(123456L);
