= Keyword leases API


=== Find keyword leases
'''
Example how to find keywords for purchase on the CallFire platform. If a keyword appears in the response, it is available for purchase.
[source,java]
 CommonFindRequest request = CommonFindRequest.create()
             .limit(1L)
             .offset(1L)
             .build();
 CallfireClient client = new CallfireClient("api_login", "api_password");
 Page<KeywordLease> leases = client.keywordLeasesApi().find(request);



=== Get keyword lease
'''
Example how to return a KeywordLease for a given keyword.
[source,java]
 //"keyword" param is required
 CallfireClient client = new CallfireClient("api_login", "api_password");
 KeywordLease keywordLease = client.keywordLeasesApi().get("test_keyword1");



=== Update keyword lease
'''
Example how update a keyword lease. Can only set autoRenew to false at this time.
[source,java]
 //"keywordLease" param is required
 KeywordLease keywordLease = new KeywordLease();
 keywordLease.setKeyword("test_keyword1");
 keywordLease.setAutoRenew(true);
 CallfireClient client = new CallfireClient("api_login", "api_password");
 client.keywordLeasesApi().update(keywordLease);
