= Keyword leases API


=== Find keyword leases
'''
Find all owned keyword leases for a user. A keyword lease is the ownership information involving a keyword.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    CommonFindRequest request = CommonFindRequest.create().build();
    Page<KeywordLease> leases = client.keywordLeasesApi().find(request);

=== Get keyword lease
'''
Example how to return a KeywordLease for a given keyword.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    KeywordLease keywordLease = client.keywordLeasesApi().get("CALLFIRE");

=== Update keyword lease
'''
Example how update a keyword lease. Can only set autoRenew to false at this time.
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    KeywordLease keywordLease = new KeywordLease();
    keywordLease.setKeyword("CALLFIRE");
    keywordLease.setAutoRenew(true);
    client.keywordLeasesApi().update(keywordLease);
