= Getting started

== Installation

Before start you should add dependency to your Java-based project. For Gradle build system add:
[source,groovy]
repositories {
    jcenter()
}
dependencies {
    compile 'com.callfire:callfire-api-client:1.4.0'
}

for Maven build add following lines to your pom xml:
[source,xml]
<!-- callfire maven repo -->
<repositories>
    <repository>
        <id>callfire-com</id>
        <name>callfire-com</name>
        <url>http://dl.bintray.com/callfire-com/maven</url>
    </repository>
</repositories>
<!-- dependency -->
<dependencies>
    <dependency>
        <groupId>com.callfire</groupId>
        <artifactId>callfire-api-client</artifactId>
        <version>1.4.0</version>
    </dependency>
</dependencies>

After these steps *callfire-api-client* should appear in your project dependencies along with other transitive ones.

In case you want to build it yourself:
[source]
    git clone https://github.com/CallFire/callfire-api-client-java.git
    cd callfire-api-client-java
    gradlew build clientFatJar

it will create 4 jars in *build/libs* directory:
[source]
callfire-api-client-1.4.0.jar
callfire-api-client-1.4.0-all.jar - client jar with all dependencies inside
callfire-api-client-1.4.0-javadoc.jar
callfire-api-client-1.4.0-sources.jar


== Overview
To create client instance just provide API login and password. API credentials should be configured on
link:https://www.callfire.com/ui/manage/access[Account -> Settings -> API Access] page. Client uses HTTPS connection
and Basic Authentication.

Example how to get account information using client:
[source,java]
public class TestCallfireApi {
    public static void main(String[] args) {
        CallfireClient client = new CallfireClient("api_login", "api_password");
        Account account = client.meApi().getAccount();
        System.out.println(account);
    }
}

.*List of API classes:*
[source,java]
    CallfireClient client = new CallfireClient("api_login", "api_password");
    client.meApi();
    client.ordersApi();
    client.keywordsApi();
    client.keywordLeasesApi();
    client.numbersApi();
    client.numberLeasesApi();
    client.agentsApi();
    client.agentGroupsApi();
    client.batchesApi();
    client.callsApi();
    client.textsApi();
    client.campaignSoundsApi();
    client.ivrBroadcastsApi();
    client.textBroadcastsApi();
    client.voiceBroadcastsApi();
    client.textAutoRepliesApi();
    client.contactsApi();
    client.contactListsApi();
    client.dncApi();
    client.dncListsApi();
    client.webhooksApi();


== Error handling
The CallFire Developers API uses standard HTTP response codes for responses. These HTTP codes indicate whether
 or not an API operation is successful.

Status Code 200 is the desired response code. A standard JSON response will follow.

Codes in the 400s range detail all of the errors a CallFire Developer could encounter while using the API. Bad
 Request, Rate Limit Reached, and Unauthorized are some of the sorts of responses in the 400s block.

Codes in the 500s range are error responses from the CallFire system. If an error has occured anywhere in the
 execution of a resource that was not due to user input, a 500 response will be returned with a corresponding
 JSON error body. In that body will contain a message detailing what went wrong.

.All API methods throw following exceptions (both are RuntimeException):
 * *CallfireApiException* - in case API cannot be queried for some reason and server returned error
 * *CallfireClientException* - in case error has occurred in client

*CallfireApiException* has *apiErrorMessage* property with details of occurred error, here is fields listing:
[source,java]
    Integer httpStatusCode;
    Integer internalCode;
    String message;
    String developerMessage;
    String helpLink;



== Debug & logging
In case you want to see requests/responses which client sends/receives from Callfire platform you should set *DEBUG*
level for *com.callfire* package, then you'll see something like that in your logs:
[source]
2015/10/21 19:02:47:355 EEST [DEBUG] RestApiClient - GET request to https://api.callfire.com/v2/me/account with params: []
2015/10/21 19:02:48:722 EEST [DEBUG] RestApiClient - received entity
{
  "id" : 1234567890,
  "email" : "john@callfire.com",
  "name" : "test",
  "firstName" : "John",
  "lastName" : "Doe",
  "permissions" : [ "ACCOUNT_HOLDER" ]
}

If you don't have any logger implementation in classpath you can simply use
commons-logging SimpleLog which are shipped with Callfire client. See example of usage below:
[source,java]
System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.SimpleLog");
System.setProperty("org.apache.commons.logging.simplelog.showdatetime", "true");
System.setProperty("org.apache.commons.logging.simplelog.log.com.callfire", "DEBUG");